__default__:
    cpus-per-task: 2
    mem-per-cpu: 4G
    partition: fast
    job-name: '{rule}.{wildcards}'
    time: '2:00:00'
    output: 'logs/{rule}.{wildcards}.out'
    error: 'logs/{rule}.{wildcards}.err'

kec_include:
    cpus-per-task: 5
    mem-per-cpu: 10G
    partition: long

kec_exclude:
    cpus-per-task: 10
    mem-per-cpu: 40G  
    partition: long

prepare_all_genomes:
    cpus-per-task: 5
    mem-per-cpu: 4G

prepare_primer3_input:
    cpus-per-task: 5
    mem-per-cpu: 4G
